db-uri = "postgres://authenticator:SnackPosSecurePass2026!@127.0.0.1:5432/snackpos"
db-schemas = "public"
db-anon-role = "web_anon"
server-port = 8000
server-host = "127.0.0.1"
jwt-secret = "SNACKPOS_JWT_SUPER_SECRET_KEY_2026_VERY_LONG_STRING_RANDOM_SECURE"
